spring:
  application:
    name: bookify

  datasource:
    url: jdbc:mysql://127.0.0.1:${MYSQL_PORT}/bookify?useSSL=false&allowPublicKeyRetrieval=true&characterEncoding=utf8&serverTimezone=Asia/Seoul
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  data:
    redis:
      host: 127.0.0.1
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}

  kafka:
    # Kafka 서버 주소 및 포트 -> 브로커 주소
    bootstrap-servers: ${KAFKA_PORT_HOST}
    producer:
      # Kafka 메시지의 Key를 문자열 직렬화
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      # Kafka 메시지의 Value를 문자열 직렬화
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      # Kafka Consumer Group ID, 커슈머 그룹 ID
      group-id: bookify-consumer
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

server:
  port: 8080